sudo: false
language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

before_install:
  - nvm install 8

install:
  - npm install --silent

before_script:
  - npm prune

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

